name: Build and Deploy

on:
  push:
    branches:
      - test  # Adjust to your test branch name in the frontend repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v2
        with:
          repository: sabirkhanek/whatsbiz-frontend  # Replace with your frontend repository URL

      - name: Build Frontend
        run: |
          # npm install
          # npx ng build --configuration=production --output-path=dist/
      
      - name: List directory structure
        run: |
          pwd
          ls

      - name: Checkout Backend Repository
        uses: actions/checkout@v2
        with:
          repository: sabirkhanek/whatsbiz-backend  # Replace with your backend repository URL
          token: ${{secrets.ACCESS_TOKEN}}
          path: './backend'
        

      - name: List directory structure
        run: |
          cd ./backend
          pwd
          ls

      - name: Create 'public' Directory in Backend
        run: |
          mkdir -p ./public

      - name: Delete Contents of Backend 'public' Directory
        run: |
          rm -rf ./public/*

      - name: Copy Frontend Build to Backend 'public' Directory
        run: |
          cp -r ../dist/* ./public/

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update frontend build"
          git push --set-upstream origin test  # Adjust to your test branch name in the backend repository
          git push origin test  # Adjust to your test branch name in the backend repository
