name: Build and Deploy

on:
  push:
    branches:
      - test  

env:
  FRONTEND_REPO: sabirkhanek/whatsbiz-frontend
  BACKEND_REPO: sabirkhanek/whatsbiz-backend
  FRONTEND_BRANCH: test
  BACKEND_BRANCH: test
  USERNAME: sabirkhanek
  GH_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.FRONTEND_REPO }}
          ref: ${{ env.FRONTEND_BRANCH }} 

      - name: Build Frontend
        run: |
          npm install
          npx ng build --configuration=production --output-path=dist/

      - name: Checkout Backend Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_BRANCH }} 
          token: ${{ env.GH_ACCESS_TOKEN }}
          path: './backend'
          fetch-depth: 0
      
      - name: Create 'public' Directory in Backend
        run: |
          mkdir -p ./public
        working-directory: 'backend'

      - name: Delete Contents of Backend 'public' Directory
        run: |
          rm -rf ./public/*
        working-directory: 'backend'

      - name: Copy Frontend Build to Backend 'public' Directory
        run: |
          cp -r ./dist/* ./backend/public/
        

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name ${{ env.USERNAME }}
          git add .
          git commit -m "AUTO: Deploy Static Frontend Bundle"
          git push --set-upstream origin ${{ env.BACKEND_BRANCH }}
          git push origin ${{ env.BACKEND_BRANCH }}
        working-directory: 'backend'
